// <auto-generated />
using System;
using AeroSentinel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AeroSentinel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.AircraftCredential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ICAO24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("VerificationKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("CredentialId");

                    b.HasIndex("ICAO24")
                        .IsUnique();

                    b.ToTable("aircraft_credential");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.FlightPlan", b =>
                {
                    b.Property<Guid>("FlightPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualArrivalTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EstimatedArrivalTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlightStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ICAO24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlightPlanId");

                    b.ToTable("flight_plan");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.FlightPlanRoute", b =>
                {
                    b.Property<Guid>("FlightPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("WaypointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlightPlanId", "Sequence");

                    b.HasIndex("WaypointId");

                    b.ToTable("flight_plan_route");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.Waypoint", b =>
                {
                    b.Property<string>("WaypointId")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("WaypointId");

                    b.ToTable("waypoint");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Entities.AircraftProfile", b =>
                {
                    b.Property<string>("ICAO24")
                        .HasColumnType("text");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ICAO24");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.ToTable("aircraft_profile");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Entities.FlightTelemetry", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("FlightPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ICAO24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Squawk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("Callsign", "TimestampUtc");

                    b.HasIndex("FlightPlanId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("flight_telemetry");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.AircraftCredential", b =>
                {
                    b.HasOne("AeroSentinel.Domain.Entities.AircraftProfile", "AircraftProfile")
                        .WithOne("AircraftCredential")
                        .HasForeignKey("AeroSentinel.Domain.Aggregates.AircraftCredential", "ICAO24")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftProfile");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Aggregates.FlightPlanRoute", b =>
                {
                    b.HasOne("AeroSentinel.Domain.Aggregates.FlightPlan", "FlightPlan")
                        .WithMany()
                        .HasForeignKey("FlightPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AeroSentinel.Domain.Aggregates.Waypoint", "Waypoint")
                        .WithMany()
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPlan");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Entities.AircraftProfile", b =>
                {
                    b.OwnsOne("AeroSentinel.Domain.Entities.AircraftPerformance", "AircraftPerformance", b1 =>
                        {
                            b1.Property<string>("AircraftProfileICAO24")
                                .HasColumnType("text");

                            b1.Property<double>("CruiseSpeedKnots")
                                .HasColumnType("double precision");

                            b1.Property<double>("MaxAltitudeFeet")
                                .HasColumnType("double precision");

                            b1.Property<double>("MaxClimbRateFeetPerMinute")
                                .HasColumnType("double precision");

                            b1.Property<double>("MaxDescentRateFeetPerMinute")
                                .HasColumnType("double precision");

                            b1.Property<double>("MaxTurnRateDegreesPerSecond")
                                .HasColumnType("double precision");

                            b1.Property<double>("MaxVelocityKnots")
                                .HasColumnType("double precision");

                            b1.HasKey("AircraftProfileICAO24");

                            b1.ToTable("aircraft_profile");

                            b1.WithOwner()
                                .HasForeignKey("AircraftProfileICAO24");
                        });

                    b.Navigation("AircraftPerformance");
                });

            modelBuilder.Entity("AeroSentinel.Domain.Entities.FlightTelemetry", b =>
                {
                    b.HasOne("AeroSentinel.Domain.Aggregates.FlightPlan", "FlightPlan")
                        .WithMany()
                        .HasForeignKey("FlightPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AeroSentinel.Domain.ValueObjects.FlightIntent", "FlightIntent", b1 =>
                        {
                            b1.Property<Guid>("FlightTelemetryMessageId")
                                .HasColumnType("uuid");

                            b1.Property<double>("IndicatedAirspeedKnots")
                                .HasColumnType("double precision");

                            b1.Property<double>("MagneticHeadingDegrees")
                                .HasColumnType("double precision");

                            b1.Property<double>("RollAngleDegrees")
                                .HasColumnType("double precision");

                            b1.Property<double>("SelectedAltitudeFeet")
                                .HasColumnType("double precision");

                            b1.Property<double>("VerticalRateFpm")
                                .HasColumnType("double precision");

                            b1.HasKey("FlightTelemetryMessageId");

                            b1.ToTable("flight_telemetry");

                            b1.WithOwner()
                                .HasForeignKey("FlightTelemetryMessageId");
                        });

                    b.OwnsOne("AeroSentinel.Domain.ValueObjects.SpatialState", "SpatialState", b1 =>
                        {
                            b1.Property<Guid>("FlightTelemetryMessageId")
                                .HasColumnType("uuid");

                            b1.Property<double>("BaroAltitudeFeet")
                                .HasColumnType("double precision");

                            b1.Property<double>("GeoAltitudeFeet")
                                .HasColumnType("double precision");

                            b1.Property<double>("GroundSpeedKnots")
                                .HasColumnType("double precision");

                            b1.Property<double>("TrackAngleDegrees")
                                .HasColumnType("double precision");

                            b1.HasKey("FlightTelemetryMessageId");

                            b1.ToTable("flight_telemetry");

                            b1.WithOwner()
                                .HasForeignKey("FlightTelemetryMessageId");

                            b1.OwnsOne("AeroSentinel.Domain.ValueObjects.AircraftGeoCoordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("SpatialStateFlightTelemetryMessageId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("SpatialStateFlightTelemetryMessageId");

                                    b2.ToTable("flight_telemetry");

                                    b2.WithOwner()
                                        .HasForeignKey("SpatialStateFlightTelemetryMessageId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.Navigation("FlightIntent")
                        .IsRequired();

                    b.Navigation("FlightPlan");

                    b.Navigation("SpatialState")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroSentinel.Domain.Entities.AircraftProfile", b =>
                {
                    b.Navigation("AircraftCredential")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
